# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0779b48eb93240595833f94f84fcb1307f91e90a07ed8ec55a291f3a73224d9ebe1a99c663f24acc259bb36ecf677826ea79534a077d3c2350e17c7c31eb8424

test:
  secret_key_base: 3efa7d79facb912b614edbaa974a9d30e3d95f24e82d70d791fe19fa92ca8f8f9cda472b85804d595684552290bc7c5f4a3b35672fd4f8aaa011c6722b596ba6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
